batch_size: 48
checkpoint: null
device: cpu
exp_name: est_coord
learning_rate: 0.0005
learning_rate_min: 1.0e-08
log_interval: 100
max_iter: 10000
model_hyperparams: {}
model_type: est_coord
num_workers: 12
obj_name: power_drill
point_num: 1024
robot: galbot
save_interval: 2500
seed: 0
val_interval: 500
val_num: 10
